export default {
  FETCH_SCHEDULE: "FETCH_SCHEDULE",
  FETCH_SCHEDULE_SUCCESS: "FETCH_SCHEDULE_SUCCESS",
  FETCH_SCHEDULE_FAILED: "FETCH_SCHEDULE_FAILED",
  UPDATE_EVENT: "UPDATE_EVENT",
  UPDATE_EVENT_SUCCESS: "UPDATE_EVENT_SUCCESS",
  UPDATE_EVENT_FAILED: "UPDATE_EVENT_FAILED",
};
